language: php
php:
  - "5.3"

matrix:
  include:
    - php: 5.3
      dist: precise


before_install:
  - composer self-update

before_script:
  - composer install

script:
  - phpunit --configuration phpunit.xml